packages:
  - "apps/*"
  - "packages/*"

overrides:
  esbuild: 0.25.12
  postcss: 8.5.26
  sharp: 0.35.4

allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - react-colorful@5.8.1
